def book_args_valid(parser):
    parser.add_argument('book_id', type=int, help='book id')
    parser.add_argument('book_name', type=str, location='json')
    parser.add_argument('author', type=str, location='json')
    parser.add_argument('text', type=str, location='json')
    parser.add_argument('image_url', type=str, location='json')
    parser.add_argument('current_number', type=int, location='json')
    parser.add_argument('number', type=int, location='json')
    parser.add_argument('category_id', type=int, location='json')
    parser.add_argument('product_id', type=int, location='json')
