"""empty message

Revision ID: a190b5212cf9
Revises: 947e590b6042
Create Date: 2024-05-06 17:21:08.988072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a190b5212cf9'
down_revision = '947e590b6042'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_login', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_login', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###
